# Generated by Django 2.0.1 on 2019-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
